export const CATEGORIES = [
  { id: 'bridesmaid', name: 'Bridesmaid Hampers', emoji: '💐', color: '#f4d0d0' },
  { id: 'wedding', name: 'Wedding Hampers', emoji: '💍', color: '#fde8e8' },
  { id: 'corporate', name: 'Corporate Gifts', emoji: '🏢', color: '#f5e6c8' },
  { id: 'birthday', name: 'Birthday Hampers', emoji: '🎂', color: '#fde8e8' },
  { id: 'baby-shower', name: 'Baby Shower', emoji: '👶', color: '#f4d0d0' },
  { id: 'festive', name: 'Festive Gifts', emoji: '✨', color: '#f5e6c8' },
  { id: 'personalized', name: 'Personalized Gifts', emoji: '🎁', color: '#fde8e8' },
  { id: 'return-gifts', name: 'Return Gifts', emoji: '🎀', color: '#f4d0d0' },
]

export const PRODUCTS = [
  {
    _id: '1',
    name: 'Pink Bliss Bridesmaid Hamper',
    category: 'bridesmaid',
    price: 2499,
    originalPrice: 3200,
    images: [
      'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80',
      'https://images.unsplash.com/photo-1607344645866-009c320b63e0?w=600&q=80',
    ],
    description: 'A luxurious curated hamper designed for your beloved bridesmaids. Includes premium skincare, scented candles, personalised accessories and more — all wrapped in our signature blush pink packaging.',
    deliveryDays: '5-7 working days',
    customizable: true,
    stock: 50,
    rating: 4.9,
    reviews: 124,
    tags: ['bestseller', 'trending'],
    includes: ['Personalised silk scrunchies', 'Rose quartz roller', 'Scented soy candle', 'Premium chocolate box', 'Custom card'],
  },
  {
    _id: '2',
    name: 'Golden Wedding Favour Box',
    category: 'wedding',
    price: 899,
    originalPrice: 1200,
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
      'https://images.unsplash.com/photo-1607344645866-009c320b63e0?w=600&q=80',
    ],
    description: 'Elegant wedding favour boxes crafted for your guests — minimum order 50 pieces. Each box is individually assembled and tied with a satin ribbon.',
    deliveryDays: '7-10 working days',
    customizable: true,
    stock: 200,
    rating: 4.8,
    reviews: 89,
    tags: ['bestseller'],
    minQty: 50,
    includes: ['Premium dry fruits', 'Personalized name card', 'Satin ribbon', 'Wax seal'],
  },
  {
    _id: '3',
    name: 'Luxury Corporate Gift Set',
    category: 'corporate',
    price: 3499,
    originalPrice: 4200,
    images: [
      'https://images.unsplash.com/photo-1513201099705-a9746072f3c3?w=600&q=80',
    ],
    description: 'Impress your clients and team with our premium corporate hamper. Logo branding available on packaging. Bulk discounts available for 20+ pieces.',
    deliveryDays: '5-7 working days',
    customizable: true,
    stock: 30,
    rating: 4.7,
    reviews: 56,
    tags: ['new'],
    includes: ['Premium dry fruit assortment', 'Branded desk accessories', 'Artisanal teas', 'Company logo packaging', 'Custom message card'],
  },
  {
    _id: '4',
    name: 'Rose Garden Birthday Hamper',
    category: 'birthday',
    price: 1899,
    originalPrice: 2400,
    images: [
      'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=600&q=80',
    ],
    description: 'Make someone\'s birthday unforgettable with this gorgeous hamper filled with treats and luxuries they\'ll love.',
    deliveryDays: '3-5 working days',
    customizable: true,
    stock: 40,
    rating: 4.9,
    reviews: 201,
    tags: ['bestseller', 'trending'],
    includes: ['Personalized mug', 'Artisan chocolates', 'Bath & body set', 'Scented candle', 'Birthday card'],
  },
  {
    _id: '5',
    name: 'Precious Baby Shower Hamper',
    category: 'baby-shower',
    price: 2799,
    originalPrice: 3500,
    images: [
      'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600&q=80',
    ],
    description: 'Celebrate the arrival of a precious new life with our thoughtfully curated baby shower hamper.',
    deliveryDays: '4-6 working days',
    customizable: true,
    stock: 25,
    rating: 4.8,
    reviews: 67,
    tags: ['new'],
    includes: ['Organic baby skincare set', 'Soft muslin wraps', 'Customized onesie', 'Baby keepsake book', 'Mommy self-care kit'],
  },
  {
    _id: '6',
    name: 'Diwali Premium Gift Box',
    category: 'festive',
    price: 1499,
    originalPrice: 1900,
    images: [
      'https://images.unsplash.com/photo-1605810230434-7631ac76ec81?w=600&q=80',
    ],
    description: 'Share the joy of Diwali with our premium festive gift box. Perfect for gifting to friends, family and colleagues.',
    deliveryDays: '3-5 working days',
    customizable: true,
    stock: 100,
    rating: 4.6,
    reviews: 312,
    tags: ['seasonal', 'trending'],
    includes: ['Assorted mithai', 'Dry fruits in decorative box', 'Diyas & candles', 'Incense set', 'Custom greeting'],
  },
]

export const TESTIMONIALS = [
  {
    _id: '1',
    name: 'Priya Sharma',
    location: 'Nagpur',
    rating: 5,
    text: 'Ordered bridesmaid hampers for my wedding and they were absolutely stunning! Every single guest asked where I got them from. The packaging is so luxurious and everything inside was premium quality.',
    occasion: 'Wedding',
    avatar: 'P',
  },
  {
    _id: '2',
    name: 'Meghna Kulkarni',
    location: 'Pune',
    rating: 5,
    text: 'The corporate gift boxes we ordered for our Diwali gifting were a massive hit with our clients! The branding was perfect and delivery was on time. Will definitely reorder.',
    occasion: 'Corporate Gifting',
    avatar: 'M',
  },
  {
    _id: '3',
    name: 'Ankita Desai',
    location: 'Mumbai',
    rating: 5,
    text: 'I ordered a birthday hamper for my best friend and she was in tears when she opened it! The personalised message card and the quality of products was exceptional. Hamper Rush is truly the best.',
    occasion: 'Birthday',
    avatar: 'A',
  },
  {
    _id: '4',
    name: 'Rohini Joshi',
    location: 'Nagpur',
    rating: 5,
    text: 'Beautiful baby shower hamper for my sister. She loved everything in it. The wrapping was so elegant and the delivery was faster than expected. Highly recommend!',
    occasion: 'Baby Shower',
    avatar: 'R',
  },
]

export const FAQS = [
  {
    q: 'Do you ship all over India?',
    a: 'Yes! We ship across India. Delivery timelines vary by location — typically 3-7 working days for most metro cities and 5-10 days for other areas.',
  },
  {
    q: 'Can I fully customize a hamper?',
    a: 'Absolutely! You can personalize names, themes, colors, and add custom notes. Some products also allow you to select specific items for your hamper.',
  },
  {
    q: 'What is the minimum order quantity for wedding favours?',
    a: 'Wedding favours require a minimum of 50 pieces. For bulk orders above 100 pieces, you get special pricing. Contact us for a custom quote.',
  },
  {
    q: 'How does the WhatsApp ordering work?',
    a: 'After placing your order online, you\'ll be redirected to WhatsApp where we confirm your order, discuss customizations in detail, and keep you updated throughout.',
  },
  {
    q: 'Do you offer corporate branding?',
    a: 'Yes! We offer logo printing, branded ribbons, and custom packaging for corporate clients. Minimum order for branded packaging is 20 pieces.',
  },
  {
    q: 'What payment methods do you accept?',
    a: 'We accept all major payment methods via Razorpay (UPI, cards, net banking) and also offer Cash on Delivery for select locations.',
  },
]
